### ISSUE TITLE
How to setup a virtual webcam ? :)

### ISSUE THREAD

**Issue by tetsuoo-online** [toyxyz/ComfyUI_toyxyz_test_nodes#10]
I'm having a load of fun with this, I'm using a RTX 3060 and I find the generation fast enough even without TAESD VAE (in fact I'm getting the exact same speed so maybe I missed something again, but that's another topic).
Now I'm trying to mimic a trick I saw on Twitter last week, using OBS Studio to setup a virtual camera connected to a different monitor running Photoshop or any drawing software... It should work but I guess I'm facing decoding issues of some sort ?
Actually even when I stop the virtual cam in OBS I'm getting the same colored noise.

Of course with the right amount of denoise the AI will get inspired no matter you give it lol
![image](https://github.com/toyxyz/ComfyUI_toyxyz_test_nodes/assets/45845308/810b75ab-55f4-4034-9297-2cde976db3be)

**Comment by tetsuoo-online** [comment]
ok answering my own question here x) Hopefully this might help others with the same concern.
It works with Load Webcam instead, this is what I do :
- Start virtual camera in OBS with the right output source (in my case, monitor #1 with Photoshop)
- Start capturing Webcam 1 with the Webcam app (in my case Webcam 0 is my default webcam)
- use Load Webcam node in ComfyUI

So of course I end up with a Photoshop window showing everything not just the image, what I found is use Image Padding with negative numbers to crop the borders and it's all good :)
![image](https://github.com/toyxyz/ComfyUI_toyxyz_test_nodes/assets/45845308/db983cc8-2fed-4ae0-a1b3-50b7bd28a239)

**Comment by toyxyz** [comment]
I'm working on an update to make selecting a camera a little simpler! 
![image](https://github.com/toyxyz/ComfyUI_toyxyz_test_nodes/assets/8006000/89d009d7-7b08-47b3-ac71-5937e66e4219)
