### ISSUE TITLE
Cant run setup.bat / run.bat

### ISSUE THREAD

**Issue by yamb0x** [toyxyz/ComfyUI_toyxyz_test_nodes#11]
Hey!

Thanks for those amazing nodes. But i cant seems to run it.
Whenever i try to launch setup.bat / run.bat nothing seems to happen, and the UI wont open.

Any idea what could it be? what i could look into? should i install something special? (Got OBS set up)
I'm running most ComfyUI workflows with no problems.

(1. It seems like the nodes are working inside ComfyUI, I'm referring the interface to choose the cam source
2.And After running setup.bat i don't see a venv folder in that path, just the cmd open and close quickly
3. I tried to gitclone and also install the plugin from the plugin manager, both leads to the same problem
4. Ive updated ComfyUI and all its extensions, but i dont have any webcam connected, just OBS)

Appreciated!
Yambo

**Comment by yamb0x** [comment]
Uninstalled older python and re-installed 3.12 and its working now

**Comment by scrufflez** [comment]
same issue, Python 3.12 did not fix mine
