### ISSUE TITLE
Workflow image not working??

### ISSUE THREAD

**Issue by LIQUIDMIND111** [toyxyz/ComfyUI_toyxyz_test_nodes#25]
im clicking and nothing happens, just error:

This private-user-images.githubusercontent.com page can’t be foundNo webpage was found for the web address:

**Comment by toyxyz** [comment]
Download the workflow image, then drag and drop it into comfyui.

**Comment by LIQUIDMIND111** [comment]
> Download the workflow image, then drag and drop it into comfyui.

yes sir, but it was not letting me download... got errors, but now i can, thanks
