### ISSUE TITLE
Memory usage/leak

### ISSUE THREAD

**Issue by MushieKings** [toyxyz/ComfyUI_toyxyz_test_nodes#27]
Memory usage keeps increasing while running. Easily eat up 10GB if running for awhile even at 1FPS and 900 width. Using window capture mode.

**Comment by toyxyz** [comment]
Thanks for the report, I'll take a look at it.

**Comment by toyxyz** [comment]
I fixed the problem, check it out and let me know if it works for you!

**Comment by MushieKings** [comment]
Yup works perfect now, thanks!

**Comment by MushieKings** [comment]
Yup works perfect now, thanks!
