### ISSUE TITLE
Webcam capture of Spout feed doesnt work

### ISSUE THREAD

**Issue by tastez** [toyxyz/ComfyUI_toyxyz_test_nodes#3]
Trying to capture a Spout feed with the webcam capture node and getting a black screen. Resolution is correct though. 
Webcam capture works correctly and captures the stream to image without issues.

**Comment by toyxyz** [comment]
The Capture Webcam node is still unstable and slow. I recommend using the Load Webcam Image node instead.

**Comment by tastez** [comment]
yep that works quite well thank you!
