### ISSUE TITLE
Where is WebcamApp ?

### ISSUE THREAD

**Issue by tetsuoo-online** [toyxyz/ComfyUI_toyxyz_test_nodes#7]
run.bat starts a console but nothing happens. I tried to run manually doing cmd>python cam.py but all I got was this error message :
Traceback (most recent call last):
  File "X:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_toyxyz_test_nodes\CaptureCam\cam.py", line 11, in <module>
    import win32clipboard
ModuleNotFoundError: No module named 'win32clipboard'

**Comment by toyxyz** [comment]
After running setup.bat, do you have a venv folder in that path?

**Comment by tetsuoo-online** [comment]
I don't know why but after updating everything using the Manager now it works ! Did you change something ? ^^
