### ISSUE TITLE
How to select 'taesd" VAE

### ISSUE THREAD

**Issue by tetsuoo-online** [toyxyz/ComfyUI_toyxyz_test_nodes#8]
I noticed that all the taesd related pth files are already in vae-approx folder, but that doesn't make them selectable in ComfyUI unless you manually copy them in VAE folder. With that done, I now get a selection of taesd encoders/decoders but I'm guessing it's not the right approach (basically walking in the dark here, I have no idea what I'm doing)
![image](https://github.com/toyxyz/ComfyUI_toyxyz_test_nodes/assets/45845308/dff3a790-47bc-43f4-a48b-0d82544f57df)

**Comment by toyxyz** [comment]
This feature is available in the latest version of ComfyUI. 
https://blog.comfyui.ca/comfyui/update/2023/11/24/Update.html
![image](https://github.com/toyxyz/ComfyUI_toyxyz_test_nodes/assets/8006000/dc4fe59e-ec87-4ccf-87c0-42c2d83f1906)

**Comment by tetsuoo-online** [comment]
Thank you, I updated and now it appears. But that means now other things like the Efficient Loader might need an update as well x) Man... Just how many times do I need to update everything haha
